package app.clothescast.data

import android.content.Context
import androidx.core.content.edit
import app.clothescast.BuildConfig
import com.google.firebase.FirebaseApp
import com.google.firebase.appcheck.AppCheckProviderFactory
import com.google.firebase.appcheck.debug.DebugAppCheckProviderFactory

/**
 * Debug builds use the Firebase Debug provider. Release-variant
 * counterpart lives in `app/src/release/...` and uses Play Integrity.
 *
 * On local builds (`BuildConfig.APP_CHECK_DEBUG_TOKEN` non-blank), we
 * pre-populate the SDK's SharedPreferences-backed debug secret so the
 * stable per-developer UUID generated by `ensureAppCheckDebugToken`
 * in `app/build.gradle.kts` is the value the SDK actually sends. The
 * `DebugAppCheckProviderFactory` doesn't expose a public API for
 * supplying the secret, so we write to the same SharedPreferences
 * slot the SDK's `StorageHelper` reads from — its `retrieveDebugSecret`
 * call inside the provider then picks up our token on the very first
 * request instead of generating its own.
 *
 * On CI builds (`APP_CHECK_DEBUG_TOKEN` blank — see `isCiBuild` in
 * the build script), we don't write anything. The SDK falls back to
 * generating its own per-install random UUID and logging it to
 * Logcat, same as the pre-PR baseline. That keeps the developer's
 * token out of anything CI produces. CI builds no debug APK at all
 * now, but it still compiles this source for `testDebugUnitTest`, so
 * the blank token is what stops the field being populated there.
 *
 * Risk note: the SharedPreferences pref-file name and key are a
 * Firebase implementation detail and could change without notice. If
 * a future `firebase-appcheck-debug` bump breaks this, the symptom
 * is "App Check 401s on debug builds" — fall back to the Logcat-grep
 * flow, pin the appcheck-debug version, or migrate to whatever new
 * mechanism the SDK adopts.
 */
fun provideAppCheckProviderFactory(context: Context): AppCheckProviderFactory {
    val token = BuildConfig.APP_CHECK_DEBUG_TOKEN
    if (token.isNotBlank()) {
        // Reverse-engineered from `firebase-appcheck-debug` 18.x bytecode:
        //
        //   StorageHelper(context, persistenceKey) opens
        //     getSharedPreferences("com.google.firebase.appcheck.debug.store.<persistenceKey>", MODE_PRIVATE)
        //   StorageHelper.saveDebugSecret(secret) writes
        //     putString("com.google.firebase.appcheck.debug.DEBUG_SECRET", secret)
        //
        // `persistenceKey` comes from `FirebaseApp.getInstance().persistenceKey`
        // — a stable, scheme-safe encoding of the FirebaseApp's name.
        val persistenceKey = FirebaseApp.getInstance().persistenceKey
        val prefName = "com.google.firebase.appcheck.debug.store.$persistenceKey"
        val prefKey = "com.google.firebase.appcheck.debug.DEBUG_SECRET"
        context.getSharedPreferences(prefName, Context.MODE_PRIVATE).edit {
            putString(prefKey, token)
        }
    }
    return DebugAppCheckProviderFactory.getInstance()
}
